version: '3'

services:
  django:
    build:
      context: .
      dockerfile: backend_api/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    # Здесь вы можете указать другие параметры конфигурации Django

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - django
    restart: always

  vite:
    image: node:latest
    working_dir: /donor-frontend
    volumes:
      - ./donor-frontend:/donor-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000" # порт Vite
