# Generated by Django 5.0.2 on 2024-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api_app', '0002_alter_user_email_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
