# Generated by Django 5.0.2 on 2024-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
